export const COUNTRY_TIMEZONES: Record<string, string> = {
  "Afghanistan": "Asia/Kabul",
  "Albania": "Europe/Tirane",
  "Algeria": "Africa/Algiers",
  "Andorra": "Europe/Andorra",
  "Angola": "Africa/Luanda",
  "Argentina": "America/Argentina/Buenos_Aires",
  "Armenia": "Asia/Yerevan",
  "Australia": "Australia/Sydney",
  "Austria": "Europe/Vienna",
  "Azerbaijan": "Asia/Baku",
  "Bahrain": "Asia/Bahrain",
  "Bangladesh": "Asia/Dhaka",
  "Belarus": "Europe/Minsk",
  "Belgium": "Europe/Brussels",
  "Bhutan": "Asia/Thimphu",
  "Bolivia": "America/La_Paz",
  "Bosnia and Herzegovina": "Europe/Sarajevo",
  "Brazil": "America/Sao_Paulo",
  "Bulgaria": "Europe/Sofia",
  "Cambodia": "Asia/Phnom_Penh",
  "Canada": "America/Toronto",
  "Chile": "America/Santiago",
  "China": "Asia/Shanghai",
  "Colombia": "America/Bogota",
  "Costa Rica": "America/Costa_Rica",
  "Croatia": "Europe/Zagreb",
  "Cuba": "America/Havana",
  "Cyprus": "Asia/Nicosia",
  "Czech Republic": "Europe/Prague",
  "Denmark": "Europe/Copenhagen",
  "Dominican Republic": "America/Santo_Domingo",
  "Ecuador": "America/Guayaquil",
  "Egypt": "Africa/Cairo",
  "Estonia": "Europe/Tallinn",
  "Ethiopia": "Africa/Addis_Ababa",
  "Finland": "Europe/Helsinki",
  "France": "Europe/Paris",
  "Georgia": "Asia/Tbilisi",
  "Germany": "Europe/Berlin",
  "Ghana": "Africa/Accra",
  "Greece": "Europe/Athens",
  "Hong Kong": "Asia/Hong_Kong",
  "Hungary": "Europe/Budapest",
  "Iceland": "Atlantic/Reykjavik",
  "India": "Asia/Kolkata",
  "Indonesia": "Asia/Jakarta",
  "Iran": "Asia/Tehran",
  "Iraq": "Asia/Baghdad",
  "Ireland": "Europe/Dublin",
  "Israel": "Asia/Jerusalem",
  "Italy": "Europe/Rome",
  "Japan": "Asia/Tokyo",
  "Jordan": "Asia/Amman",
  "Kazakhstan": "Asia/Almaty",
  "Kenya": "Africa/Nairobi",
  "Kuwait": "Asia/Kuwait",
  "Latvia": "Europe/Riga",
  "Lebanon": "Asia/Beirut",
  "Lithuania": "Europe/Vilnius",
  "Luxembourg": "Europe/Luxembourg",
  "Malaysia": "Asia/Kuala_Lumpur",
  "Maldives": "Indian/Maldives",
  "Malta": "Europe/Malta",
  "Mexico": "America/Mexico_City",
  "Monaco": "Europe/Monaco",
  "Mongolia": "Asia/Ulaanbaatar",
  "Morocco": "Africa/Casablanca",
  "Myanmar": "Asia/Yangon",
  "Nepal": "Asia/Kathmandu",
  "Netherlands": "Europe/Amsterdam",
  "New Zealand": "Pacific/Auckland",
  "Nigeria": "Africa/Lagos",
  "North Korea": "Asia/Pyongyang",
  "Norway": "Europe/Oslo",
  "Oman": "Asia/Muscat",
  "Pakistan": "Asia/Karachi",
  "Peru": "America/Lima",
  "Philippines": "Asia/Manila",
  "Poland": "Europe/Warsaw",
  "Portugal": "Europe/Lisbon",
  "Qatar": "Asia/Qatar",
  "Romania": "Europe/Bucharest",
  "Russia": "Europe/Moscow",
  "Saudi Arabia": "Asia/Riyadh",
  "Singapore": "Asia/Singapore",
  "Slovakia": "Europe/Bratislava",
  "Slovenia": "Europe/Ljubljana",
  "South Africa": "Africa/Johannesburg",
  "South Korea": "Asia/Seoul",
  "Spain": "Europe/Madrid",
  "Sri Lanka": "Asia/Colombo",
  "Sweden": "Europe/Stockholm",
  "Switzerland": "Europe/Zurich",
  "Taiwan": "Asia/Taipei",
  "Thailand": "Asia/Bangkok",
  "Turkey": "Europe/Istanbul",
  "Ukraine": "Europe/Kiev",
  "United Arab Emirates": "Asia/Dubai",
  "United Kingdom": "Europe/London",
  "United States": "America/New_York",
  "Vatican City": "Europe/Vatican",
  "Venezuela": "America/Caracas",
  "Vietnam": "Asia/Ho_Chi_Minh"
};
